name: dependencies-analysis-pipeline

on:
  workflow_call:
    inputs:
      workdir:
        description: The working directory for the job
        required: false
        default: './'
        type: string
      organization:
        description: Dependencies Analysis
        required: false
        default: 'davivienda-colombia'
        type: string
      project_name:
        description: The name of the project
        required: true
        type: string
      language:
        description: The programming language of the project
        required: false
        default: 'JavaScript, TypeScript, node.js'
        type: string
      package_manager:
        description: The package manager used in the project
        required: false
        default: 'npm'
        type: string
      node-version:
        description: The Node.js version to use
        required: false
        default: '18.x'
        type: string
      build_command:
        description: The command to build the project
        required: false
        default: 'npm ci'
        type: string
      

jobs:
  build-dependencies-analysis:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: |
          cd ${{ inputs.workdir }}
          ${{ inputs.build_command }}
      # Validación con NPM Outdated Action
      - name: NPM Outdated Check
        uses: cssnr/npm-outdated-action@master
        continue-on-error: true
        with:
          columns: n,c,w,l
          # Report if Latest > Wanted
          latest: true
          # Comment Heading
          heading: NPM Outdated Check
          # Details Open by Default
          open: true
          # Show npm-check-updates Output
          ncu: true
          # Show npm update --dry-run Output
          update: true
          # Use Link for Names
          link: true
          # Add Summary to Job
          summary: true
          # GitHub Token
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # Validación con NPM Audit
      - name: NPM Audit Comment
        uses: wx-jayesh/actions-npm-audit-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


    
      